### ISSUE TITLE
cd file or direcotry not found

### ISSUE THREAD

**Issue by VitoHusky** [jenkinsci/ssh2easy-plugin#4]
hello there, 

im using the following script to automatically update my symfony script.
- Login works
- Script creation (.sh) works
- Execution of script works.

SCript:
cd /var/www/virtual/xxx/testing/htdocs/
git pull
composer install
php bin/console doctrine:schema:update --force
php bin/console cache:clear --env=prod
php bin/console cache:clear --env=dev
echo "build done"

Output:
-bash: cd: /var/www/virtual/xxx/testing/htdocs/
: No such file or directory
' is not a git command. See 'git --help'.

Did you mean this?
	pull
[30;43mDo not run Composer as root/super user! See https://getcomposer.org/root for details[39;49m

[37;41m                                                                  [39;49m
[37;41m  [Symfony\Component\Console\Exception\CommandNotFoundException]  [39;49m
[37;41m  Command "install
" is not defined.                              [39;49m
[37;41m  Did you mean this?                                              [39;49m
[37;41m      install                                                     [39;49m
[37;41m                                                                  [39;49m

Could not open input file: bin/console
Could not open input file: bin/console
Could not open input file: bin/console
build done

Is it using a wrong shell or something?

I tried to set the shell executable of jenkins to "/bin/bash" but this didnt do the trick as well

**Comment by JerryCai** [comment]
@Levitas  Sorry for so late reply, from your logs , It seems your command line end with \n ? please copy the command lines from text or change the another browser to try again ?
